
package pt.indra.mygiaf.services.ist.istexternalservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ISTExternalServices", targetNamespace = "http://ist.services.mygiaf.indra.pt/ISTExternalServices", wsdlLocation = "http://mygiaf.adm:8080/mygiaf/services/ISTExternalServices?wsdl")
public class ISTExternalServices
    extends Service
{

    private final static URL ISTEXTERNALSERVICES_WSDL_LOCATION;
    private final static WebServiceException ISTEXTERNALSERVICES_EXCEPTION;
    private final static QName ISTEXTERNALSERVICES_QNAME = new QName("http://ist.services.mygiaf.indra.pt/ISTExternalServices", "ISTExternalServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://mygiaf.adm:8080/mygiaf/services/ISTExternalServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISTEXTERNALSERVICES_WSDL_LOCATION = url;
        ISTEXTERNALSERVICES_EXCEPTION = e;
    }

    public ISTExternalServices() {
        super(__getWsdlLocation(), ISTEXTERNALSERVICES_QNAME);
    }

    public ISTExternalServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISTEXTERNALSERVICES_QNAME, features);
    }

    public ISTExternalServices(URL wsdlLocation) {
        super(wsdlLocation, ISTEXTERNALSERVICES_QNAME);
    }

    public ISTExternalServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISTEXTERNALSERVICES_QNAME, features);
    }

    public ISTExternalServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISTExternalServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISTExternalServicesPortType
     */
    @WebEndpoint(name = "ISTExternalServicesHttpPort")
    public ISTExternalServicesPortType getISTExternalServicesHttpPort() {
        return super.getPort(new QName("http://ist.services.mygiaf.indra.pt/ISTExternalServices", "ISTExternalServicesHttpPort"), ISTExternalServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISTExternalServicesPortType
     */
    @WebEndpoint(name = "ISTExternalServicesHttpPort")
    public ISTExternalServicesPortType getISTExternalServicesHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ist.services.mygiaf.indra.pt/ISTExternalServices", "ISTExternalServicesHttpPort"), ISTExternalServicesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISTEXTERNALSERVICES_EXCEPTION!= null) {
            throw ISTEXTERNALSERVICES_EXCEPTION;
        }
        return ISTEXTERNALSERVICES_WSDL_LOCATION;
    }

}
